package com.scb.tripsystem.service;

import com.scb.tripsystem.entity.*;
import com.scb.tripsystem.repository.ApplicationRepository;
import com.scb.tripsystem.repository.ApprovalHistoryRepository;
import com.scb.tripsystem.repository.BatchRepository;
import java.util.Comparator;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class ApplicationService {

    private final ApplicationRepository applicationRepository;
    private final ApprovalHistoryRepository approvalHistoryRepository;
    private final BatchRepository batchRepository;
    private final StatusService statusService;
    private final TripService tripService;

    public ApplicationService(
            ApplicationRepository applicationRepository,
            ApprovalHistoryRepository approvalHistoryRepository,
            BatchRepository batchRepository,
            StatusService statusService,
            TripService tripService) {

        this.applicationRepository =
                applicationRepository;

        this.approvalHistoryRepository =
                approvalHistoryRepository;

        this.batchRepository =
                batchRepository;

        this.statusService =
                statusService;

        this.tripService =
                tripService;
    }


    // =========================================================
    // EMPLOYEE - APPLY FOR TRIP
    // =========================================================

    @Transactional
    public Application applyForTrip(

            Long tripId,
            Long batchId,
            Employee employee,
            String transportType,
            String pickupPoint,
            Integer roomsRequested,
            BigDecimal totalPrice,
            List<ApplicationParticipant> participants) {

        Trip trip =
                tripService.getTripById(tripId);


        // =====================================================
        // PREVENT DUPLICATE APPLICATION
        // =====================================================

        if (applicationRepository
                .existsByEmployee_EmployeeIdAndTrip_TripId(
                        employee.getEmployeeId(),
                        tripId)) {

            throw new RuntimeException(
                    "Employee has already applied for this trip"
            );
        }


        // =====================================================
        // TRIP MUST BE ACTIVE
        // =====================================================

        if (trip.getStatus() == null ||
                !"ACTIVE".equals(
                        trip.getStatus().getStatusName())) {

            throw new RuntimeException(
                    "You can only apply to ACTIVE trips"
            );
        }


        // =====================================================
        // REGISTRATION PERIOD
        // =====================================================

        LocalDateTime now =
                LocalDateTime.now();

        if (trip.getRegistrationOpen() != null &&
                now.isBefore(
                        trip.getRegistrationOpen())) {

            throw new RuntimeException(
                    "Registration has not opened yet"
            );
        }

        if (trip.getRegistrationClose() != null &&
                now.isAfter(
                        trip.getRegistrationClose())) {

            throw new RuntimeException(
                    "Registration is closed for this trip"
            );
        }


        // =====================================================
        // BATCH
        // =====================================================

        Batch batch =
                batchRepository.findById(batchId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Batch not found"
                                )
                        );


        if (batch.getTrip() == null ||
                batch.getTrip().getTripId() == null ||
                !batch.getTrip()
                        .getTripId()
                        .equals(tripId)) {

            throw new RuntimeException(
                    "Batch does not belong to this trip"
            );
        }


        // =====================================================
        // CREATE APPLICATION
        //
        // createdAt is automatically generated by
        // @CreationTimestamp in Application entity.
        // We intentionally DO NOT take submission time
        // from Angular/frontend.
        // =====================================================

        Application application =
                new Application();

        application.setEmployee(
                employee
        );

        application.setTrip(
                trip
        );

        application.setBatch(
                batch
        );

        application.setTransportType(
                transportType
        );

        application.setPickupPoint(
                pickupPoint
        );

        application.setRoomsRequested(
                roomsRequested != null
                        ? roomsRequested
                        : 1
        );

        application.setTotalPrice(
                totalPrice
        );

        application.setStatus(
                statusService.getByName(
                        "PENDING_MANAGER"
                )
        );


        // =====================================================
        // PARTICIPANTS
        // =====================================================

        if (participants != null) {

            for (
                    ApplicationParticipant p
                    : participants
            ) {

                p.setApplication(
                        application
                );

                application
                        .getParticipants()
                        .add(p);
            }
        }


        // =====================================================
        // SAVE
        // =====================================================

        Application saved =
                applicationRepository.save(
                        application
                );


        // =====================================================
        // HISTORY
        // =====================================================

        saveHistory(
                saved,
                employee,
                "EMPLOYEE",
                "APPLIED",
                "Employee submitted application"
        );


        return saved;
    }


    // =========================================================
    // EMPLOYEE - MY HISTORY
    // =========================================================

    public List<Application> getMyHistory(
            Employee employee) {

        List<String> historyStatuses = List.of(
                "SELECTED",
                "WAITLIST",
                "NOT_SELECTED",
                "REJECTED_BY_MANAGER"
        );

        return applicationRepository
                .findHistoryByEmployeeId(
                        employee.getEmployeeId(),
                        historyStatuses
                );
    }


    // =========================================================
    // LINE MANAGER
    // =========================================================

    public List<Application>
    getApplicationsForManager(
            Long managerId) {

        return applicationRepository
                .findByEmployee_Manager_EmployeeId(
                        managerId
                );
    }


    // =========================================================
    // LINE MANAGER - PENDING TASKS
    // =========================================================

    public List<Application>
    getPendingApplicationsForManager(
            Long managerId) {

        return applicationRepository
                .findByEmployee_Manager_EmployeeIdAndStatus_StatusName(
                        managerId,
                        "PENDING_MANAGER"
                );
    }


    // =========================================================
    // LINE MANAGER - APPROVE
    // =========================================================

    @Transactional
    public Application approveByManager(

            Long applicationId,
            Employee manager,
            String comments) {

        Application application =
                getApplicationById(
                        applicationId,
                        manager
                );


        // =====================================================
        // DIRECT MANAGER CHECK
        // =====================================================

        validateManagerOwnership(
                application,
                manager
        );


        // =====================================================
        // STATUS CHECK
        // =====================================================

        if (application.getStatus() == null ||
                !"PENDING_MANAGER".equals(
                        application
                                .getStatus()
                                .getStatusName())) {

            throw new RuntimeException(
                    "Application is not in PENDING_MANAGER status"
            );
        }


        // =====================================================
        // APPROVE
        // =====================================================

        application.setStatus(
                statusService.getByName(
                        "APPROVED_BY_MANAGER"
                )
        );


        Application saved =
                applicationRepository.save(
                        application
                );


        // =====================================================
        // APPROVAL HISTORY
        // =====================================================

        saveHistory(
                saved,
                manager,
                "LINE_MANAGER",
                "APPROVED",
                comments
        );


        return saved;
    }


    // =========================================================
    // LINE MANAGER - REJECT
    // =========================================================

    @Transactional
    public Application rejectByManager(

            Long applicationId,
            Employee manager,
            String comments) {

        Application application =
                getApplicationById(
                        applicationId,
                        manager
                );


        // =====================================================
        // DIRECT MANAGER CHECK
        // =====================================================

        validateManagerOwnership(
                application,
                manager
        );


        // =====================================================
        // STATUS CHECK
        // =====================================================

        if (application.getStatus() == null ||
                !"PENDING_MANAGER".equals(
                        application
                                .getStatus()
                                .getStatusName())) {

            throw new RuntimeException(
                    "Application is not in PENDING_MANAGER status"
            );
        }


        // =====================================================
        // REJECT
        // =====================================================

        application.setStatus(
                statusService.getByName(
                        "REJECTED_BY_MANAGER"
                )
        );


        Application saved =
                applicationRepository.save(
                        application
                );


        // =====================================================
        // APPROVAL HISTORY
        // =====================================================

        saveHistory(
                saved,
                manager,
                "LINE_MANAGER",
                "REJECTED",
                comments
        );


        return saved;
    }


    // =========================================================
    // HR ADMIN - READY FOR SELECTION
    // =========================================================

    public List<Application>
    getApplicationsReadyForSelection(
            Long tripId) {

        return applicationRepository
                .findByTrip_TripIdAndStatus_StatusName(
                        tripId,
                        "APPROVED_BY_MANAGER"
                );
    }


    // =========================================================
    // HR ADMIN - SELECTION
    // =========================================================

    @Transactional
    public void performSelection(

            Long tripId,
            String method,
            Employee hrUser) {


        // =====================================================
        // VALIDATE METHOD
        // =====================================================

        if (method == null ||
                (
                        !"FIFO".equalsIgnoreCase(method)
                                &&
                                !"RANDOM".equalsIgnoreCase(method)
                )) {

            throw new RuntimeException(
                    "Selection method must be FIFO or RANDOM"
            );
        }


        String selectionMethod =
                method.trim().toUpperCase();


        // =====================================================
        // GET CANDIDATES
        //
        // For FIFO we deliberately query the database ordered
        // by createdAt ASC.
        //
        // For RANDOM we load the normal candidates and shuffle.
        // =====================================================

        List<Application> candidates;

        if ("FIFO".equals(selectionMethod)) {

            candidates =
                    new ArrayList<>(
                            applicationRepository
                                    .findForFifoSelection(
                                            tripId,
                                            "APPROVED_BY_MANAGER"
                                    )
                    );

        } else {

            candidates =
                    new ArrayList<>(
                            getApplicationsReadyForSelection(
                                    tripId
                            )
                    );

            Collections.shuffle(
                    candidates
            );
        }


        if (candidates.isEmpty()) {

            throw new RuntimeException(
                    "No applications ready for selection"
            );
        }


        // =====================================================
        // VERIFY ALL APPLICATIONS BELONG TO THE TRIP
        // =====================================================

        for (Application app : candidates) {

            if (app.getTrip() == null ||
                    app.getTrip().getTripId() == null ||
                    !app.getTrip()
                            .getTripId()
                            .equals(tripId)) {

                throw new RuntimeException(
                        "Application does not belong to the selected trip"
                );
            }
        }


        // =====================================================
        // SET IN_SELECTION
        // =====================================================

        Status inSelectionStatus =
                statusService.getByName(
                        "IN_SELECTION"
                );


        for (Application app : candidates) {

            app.setStatus(
                    inSelectionStatus
            );

            app.setSelectionMethod(
                    selectionMethod
            );

            applicationRepository.save(
                    app
            );

            saveHistory(
                    app,
                    hrUser,
                    "HR_ADMIN",
                    "SELECTION_STARTED",
                    "Selection method: "
                            + selectionMethod
            );
        }


        // =====================================================
        // LOAD FINAL STATUSES
        // =====================================================

        Status selectedStatus =
                statusService.getByName(
                        "SELECTED"
                );

        Status waitlistStatus =
                statusService.getByName(
                        "WAITLIST"
                );

        Status notSelectedStatus =
                statusService.getByName(
                        "NOT_SELECTED"
                );


        // =====================================================
        // TRACK REMAINING ROOMS PER BATCH
        // =====================================================

        Map<Long, Integer> remainingRooms =
                new HashMap<>();


        // =====================================================
        // ALLOCATE
        // =====================================================

        for (Application app : candidates) {

            Batch batch =
                    app.getBatch();


            if (batch == null ||
                    batch.getBatchId() == null) {

                throw new RuntimeException(
                        "Application "
                                + app.getApplicationId()
                                + " has no valid batch"
                );
            }


            Long batchId =
                    batch.getBatchId();


            // -------------------------------------------------
            // LOAD CAPACITY ONCE
            // -------------------------------------------------

            if (!remainingRooms.containsKey(
                    batchId)) {

                Integer numberOfRooms =
                        batch.getNumberOfRooms();

                if (numberOfRooms == null ||
                        numberOfRooms <= 0) {

                    throw new RuntimeException(
                            "Batch "
                                    + batchId
                                    + " has invalid number of rooms"
                    );
                }

                remainingRooms.put(
                        batchId,
                        numberOfRooms
                );
            }


            int roomsAvailable =
                    remainingRooms.get(
                            batchId
                    );


            // -------------------------------------------------
            // REQUESTED ROOMS
            // -------------------------------------------------

            int roomsRequested =
                    app.getRoomsRequested() != null
                            &&
                            app.getRoomsRequested() > 0
                            ?
                            app.getRoomsRequested()
                            :
                            1;


            // =================================================
            // SELECTED
            // =================================================

            if (roomsRequested <= roomsAvailable) {

                app.setStatus(
                        selectedStatus
                );

                app.setSelectedAt(
                        LocalDateTime.now()
                );

                app.setSelectionMethod(
                        selectionMethod
                );

                remainingRooms.put(
                        batchId,
                        roomsAvailable
                                - roomsRequested
                );

                applicationRepository.save(
                        app
                );

                saveHistory(
                        app,
                        hrUser,
                        "HR_ADMIN",
                        "SELECTED",
                        "Application selected using "
                                + selectionMethod
                                + ". Rooms requested: "
                                + roomsRequested
                );

            }


            // =================================================
            // WAITLIST
            // =================================================

            else {

                app.setStatus(
                        waitlistStatus
                );

                app.setSelectionMethod(
                        selectionMethod
                );

                app.setSelectedAt(
                        null
                );

                applicationRepository.save(
                        app
                );

                saveHistory(
                        app,
                        hrUser,
                        "HR_ADMIN",
                        "WAITLISTED",
                        "Application moved to waitlist. "
                                + "Rooms requested: "
                                + roomsRequested
                                + ", rooms remaining: "
                                + roomsAvailable
                );
            }
        }


        // =====================================================
        // FINAL SAVE
        // =====================================================

        applicationRepository.saveAll(
                candidates
        );
    }


    @Transactional
    public void performSelection(
            Long tripId,
            Long batchId,
            String method,
            Employee hrUser) {

        if (method == null ||
                (!"FIFO".equalsIgnoreCase(method)
                        && !"RANDOM".equalsIgnoreCase(method))) {

            throw new RuntimeException(
                    "Selection method must be FIFO or RANDOM"
            );
        }

        String selectionMethod =
                method.trim().toUpperCase();

        // =====================================================
        // GET ONLY APPLICATIONS FOR THIS TRIP + BATCH
        // AND ONLY THOSE APPROVED BY LINE MANAGER
        // =====================================================

        List<Application> candidates =
                new ArrayList<>(
                        applicationRepository
                                .findByTrip_TripIdAndBatch_BatchIdAndStatus_StatusName(
                                        tripId,
                                        batchId,
                                        "APPROVED_BY_MANAGER"
                                )
                );

        if (candidates.isEmpty()) {
            throw new RuntimeException(
                    "No applications ready for selection in the approved batch"
            );
        }

        // =====================================================
        // ORDER
        // =====================================================

        if ("FIFO".equals(selectionMethod)) {

            candidates.sort(
                    Comparator.comparing(
                            Application::getCreatedAt,
                            Comparator.nullsLast(
                                    Comparator.naturalOrder()
                            )
                    )
            );

        } else {

            Collections.shuffle(candidates);
        }

        // =====================================================
        // VERIFY TRIP + BATCH
        // =====================================================

        for (Application app : candidates) {

            if (app.getTrip() == null ||
                    !tripId.equals(
                            app.getTrip().getTripId()
                    )) {

                throw new RuntimeException(
                        "Application does not belong to the selected trip"
                );
            }

            if (app.getBatch() == null ||
                    !batchId.equals(
                            app.getBatch().getBatchId()
                    )) {

                throw new RuntimeException(
                        "Application does not belong to the selected batch"
                );
            }
        }

        // =====================================================
        // LOAD STATUSES
        // =====================================================

        Status inSelectionStatus =
                statusService.getByName("IN_SELECTION");

        Status selectedStatus =
                statusService.getByName("SELECTED");

        Status waitlistStatus =
                statusService.getByName("WAITLIST");

        // =====================================================
        // MARK IN SELECTION
        // =====================================================

        for (Application app : candidates) {

            app.setStatus(inSelectionStatus);

            app.setSelectionMethod(
                    selectionMethod
            );

            applicationRepository.save(app);

            saveHistory(
                    app,
                    hrUser,
                    "HR_ADMIN",
                    "SELECTION_STARTED",
                    "Selection method: "
                            + selectionMethod
                            + ", Batch ID: "
                            + batchId
            );
        }

        // =====================================================
        // BATCH CAPACITY
        // =====================================================

        Batch batch =
                candidates.get(0).getBatch();

        Integer numberOfRooms =
                batch.getNumberOfRooms();

        if (numberOfRooms == null ||
                numberOfRooms <= 0) {

            throw new RuntimeException(
                    "Batch "
                            + batchId
                            + " has invalid number of rooms"
            );
        }

        int remainingRooms =
                numberOfRooms;

        // =====================================================
        // ALLOCATE
        // =====================================================

        for (Application app : candidates) {

            int roomsRequested =
                    app.getRoomsRequested() != null &&
                            app.getRoomsRequested() > 0
                            ? app.getRoomsRequested()
                            : 1;

            if (roomsRequested <= remainingRooms) {

                app.setStatus(selectedStatus);

                app.setSelectedAt(
                        LocalDateTime.now()
                );

                app.setSelectionMethod(
                        selectionMethod
                );

                remainingRooms -= roomsRequested;

                applicationRepository.save(app);

                saveHistory(
                        app,
                        hrUser,
                        "HR_ADMIN",
                        "SELECTED",
                        "Application selected using "
                                + selectionMethod
                                + ". Rooms requested: "
                                + roomsRequested
                );

            } else {

                app.setStatus(waitlistStatus);

                app.setSelectionMethod(
                        selectionMethod
                );

                app.setSelectedAt(null);

                applicationRepository.save(app);

                saveHistory(
                        app,
                        hrUser,
                        "HR_ADMIN",
                        "WAITLISTED",
                        "Application moved to waitlist. "
                                + "Rooms requested: "
                                + roomsRequested
                                + ", rooms remaining: "
                                + remainingRooms
                );
            }
        }

        applicationRepository.saveAll(candidates);
    }

    // =========================================================
    // COMMON - GET APPLICATION
    // =========================================================

    public Application getApplicationById(

            Long applicationId,
            Employee employee) {

        Application application =
                applicationRepository
                        .findById(applicationId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Application not found"
                                )
                        );


        // =====================================================
        // OWNER
        // =====================================================

        if (application.getEmployee() != null &&
                application.getEmployee()
                        .getEmployeeId()
                        .equals(
                                employee.getEmployeeId()
                        )) {

            return application;
        }


        // =====================================================
        // LINE MANAGER
        //
        // A manager can access an application only if the
        // application's employee reports directly to him.
        // =====================================================

        if ("LINE_MANAGER".equalsIgnoreCase(
                getEmployeeRole(employee))) {

            Employee applicationEmployee =
                    application.getEmployee();

            if (applicationEmployee != null &&
                    applicationEmployee.getManager() != null &&
                    applicationEmployee
                            .getManager()
                            .getEmployeeId()
                            .equals(
                                    employee.getEmployeeId()
                            )) {

                return application;
            }
        }


        throw new RuntimeException(
                "Access denied. You are not allowed to access this application."
        );
    }


    // =========================================================
    // EMPLOYEE - MY REQUESTS
    // =========================================================

    public List<Application>
    getMyApplications(
            Employee employee) {

        return applicationRepository
                .findMyApplicationsOrdered(
                        employee.getEmployeeId()
                );
    }


    // =========================================================
    // APPLICATION HISTORY
    // =========================================================

    public List<ApprovalHistory>
    getApplicationHistory(
            Long applicationId) {

        return approvalHistoryRepository
                .findByApplication_ApplicationId(
                        applicationId
                );
    }


    // =========================================================
    // MANAGER OWNERSHIP VALIDATION
    // =========================================================

    private void validateManagerOwnership(

            Application application,
            Employee manager) {

        if (application == null ||
                application.getEmployee() == null) {

            throw new RuntimeException(
                    "Application employee information is missing"
            );
        }


        Employee applicationEmployee =
                application.getEmployee();


        if (applicationEmployee.getManager() == null) {

            throw new RuntimeException(
                    "This employee has no assigned manager"
            );
        }


        if (!applicationEmployee
                .getManager()
                .getEmployeeId()
                .equals(
                        manager.getEmployeeId()
                )) {

            throw new RuntimeException(
                    "You are not the manager of this employee"
            );
        }
    }


    // =========================================================
    // GET EMPLOYEE ROLE
    // =========================================================

    private String getEmployeeRole(
            Employee employee) {

        if (employee == null ||
                employee.getRole() == null) {

            return "";
        }

        return employee
                .getRole()
                .getRoleName();
    }



    // =========================================================
// LINE MANAGER - APPROVAL HISTORY
// =========================================================

    public List<ApprovalHistory> getManagerApprovalHistory(
            Employee manager) {

        return approvalHistoryRepository
                .findByActionBy_EmployeeIdAndRoleAtActionOrderByActionAtDesc(
                        manager.getEmployeeId(),
                        "LINE_MANAGER"
                );
    }


    // =========================================================
    // SAVE APPROVAL HISTORY
    // =========================================================

    private void saveHistory(

            Application application,

            Employee actionBy,

            String role,

            String action,

            String comments) {

        ApprovalHistory history =
                new ApprovalHistory();


        history.setApplication(
                application
        );


        history.setActionBy(
                actionBy
        );


        history.setRoleAtAction(
                role
        );


        history.setAction(
                action
        );


        history.setComments(
                comments
        );


        history.setActionAt(
                LocalDateTime.now()
        );


        approvalHistoryRepository.save(
                history
        );
    }
}